k_shots: 5
num_tasks: 6

img_channels: 3
n_channels: 64
n_groups: 32

# Generator args
g_channel_multipliers: [1, 2, 2, 4]
g_is_attention: [False, False, False, True]
beta_schedule: linear

# Discriminator args
d_n_classes: 1
d_resolution: 256
d_lr: 0.0001

# Training parameters
adam_betas: [0.5, 0.999]
gen_lr: 0.0001
weight_decay: 0.001
step_size: 100

total_epochs: 6000
model_folder_path: ./model_weights/6000_5shot_psnr/
train_frame_path: /impacs/yuz19/data/shanghaitech/training/frames_split
test_frame_path: /impacs/yuz19/data/shanghaitech/testing/frames_split
gt_folder: /impacs/yuz19/data/shanghaitech/testing/test_frame_mask
images_folder: ./results/6000_5shot_psnr
tensorboard_folder: ./logdir/6000_5shot_psnr

