k_shots: 5
num_tasks: 6
n_groups: 32

# unet args
unet_args:
  image_channels: 3
  n_channels: 64
  ch_mults: [1, 2, 2, 4]
  is_attn: [False, False, False, True]

img_channels: 3
n_channels: 64
attention_dim: 64
patch_dim: [4,4]
heads: 8

# Diffusion args
diff_args:  
  beta_schedule: linear

# Transformer args
ff_args:
  dim: 64 # embedding dimensions (total)
  hidden_dim: 128 # 64 * 2
  dropout: 0.0

# Spatial Attention args
sp_attn_args:
  dim: 64
  heads: 1
  dropout: 0.0
  sp_dim: [32, 32]
  dim_head: 64

# Temporal Attention args
tp_attn_args:
  dim: 64
  heads: 1
  dropout: 0.0
  dim_head: 64

# Encoder args
encoder_args:
  ch: 64
  ch_mult: [1,2,2,4]
  out_ch: 3
  in_channels: 3
  num_res_blocks: 2
  dropout: 0.0
  attn_resolutions: []
  resolution: 64 # attention resolution
  z_channels: 64
  double_z: False

# Decoder args
decoder_args:
  ch: 64
  ch_mult: [1,2,2,4]
  out_ch: 3
  in_channels: 3
  num_res_blocks: 2
  dropout: 0.0
  # 8, 16, 32, 64
  attn_resolutions: []
  resolution: 64 # attention resolution
  z_channels: 64
  double_z: False
  use_timestep: False


# Discriminator args
discriminator_args:
  n_classes: 1
  resolution: 256
  D_lr: 0.0001

# Training parameters
adam_betas: [0.5, 0.999]
gen_lr: 0.0001
weight_decay: 0.001
step_size: 100

total_epochs: 2000
model_folder_path: ./model_weights/trial_2/
train_frame_path: /impacs/yuz19/data/shanghaitech/training/frames_split
test_frame_path: /impacs/yuz19/data/shanghaitech/testing/frames_split
gt_folder: /impacs/yuz19/data/shanghaitech/testing/test_frame_mask
images_folder: ./results/trial_2
tensorboard_folder: ./logdir/trial_2

