k_shots: 5
num_tasks: 6
n_groups: 32

# unet args
unet_args:
  image_channels: 3
  n_channels: 64
  ch_mults: [1, 2, 2, 4]
  is_attn: [False, False, False, True]

img_channels: 3
n_channels: 64
attention_dim: 64
patch_dim: [4,4]
heads: 8

# Diffusion args
diff_args:  
  beta_schedule: linear

# Transformer args
ff_args:
  dim: 6 # embedding dimensions (total)
  hidden_dim: 12 # 64 * 2
  dropout: 0.0
  out_dim: 3

# Spatial Attention args
sp_attn_args:
  dim: 6
  heads: 1
  dropout: 0.0
  sp_dim: [32, 32]
  dim_head: 32

# Temporal Attention args
tp_attn_args:
  dim: 6
  heads: 1
  dropout: 0.0
  dim_head: 32


# Discriminator args
discriminator_args:
  n_classes: 1
  resolution: 256
  D_lr: 0.0001

# Training parameters
adam_betas: [0.5, 0.999]
gen_lr: 4.5e-06
weight_decay: 0.01
step_size: 100


# autoencoder_args:
#   embed_dim: 3
#   monitor: "val/rec_loss"
#   ckpt_path: "./ckpts/kl-f4/model.ckpt"
#   ignore_keys: ["quant_conv", "loss"]
#   ddconfig:
#     double_z: True
#     z_channels: 3
#     resolution: 256
#     in_channels: 3
#     out_ch: 3
#     ch: 128
#     ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
#     num_res_blocks: 2
#     attn_resolutions: [ ]
#     dropout: 0.0
#   lossconfig:
#     target: taming.modules.losses.DummyLoss
  # lossconfig:
  #   target: ldm.losses.LPIPSWithDiscriminator
  #   params:
  #     disc_start: 50001
  #     kl_weight: 0.000001
  #     disc_weight: 0.5
ckpt_path: "./ckpts/vq-f4/model.ckpt" 
encoder_decoder_args:
    double_z: True
    z_channels: 3
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
total_epochs: 2000
model_folder_path: ./model_weights/trial_2/
train_frame_path: /impacs/yuz19/data/shanghaitech/training/frames_split
test_frame_path: /impacs/yuz19/data/shanghaitech/testing/frames_split
gt_folder: /impacs/yuz19/data/shanghaitech/testing/test_frame_mask
images_folder: ./results/trial_2
tensorboard_folder: ./logdir/trial_2

